server:
  port: 8085
  servlet:
    context-path: /batch-processor

spring:
  batch:
    job:
      enabled: false
  datasource:
    url: jdbc:h2:mem:public;DB_CLOSE_ON_EXIT=FALSE
    username: sa
#    password: password
    driverClassName: org.h2.Driver
  h2:
    console.enabled: true
  main:
    banner-mode: off
  jmx:
    default-domain: /batch-processor
  jpa:
    defer-datasource-initialization: false
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
    open-in-view: true
    properties:
      hibernate:
        default_schema: public
        show_sql: true
    show-sql: true
  servlet:
    multipart:
      max-file-size: 80MB
      max-request-size: 80MB

batch:
  tasbetc:
    process:
      service:
        beginningLinesToSkip: 2
        chunkSize: 25
        csvFileHeaders: componentTasSP,componentTasATA,componentTasAID,componentTasBPOA,componentTasEPOA,componentTasA,componentTasMain,componentTasSub,adminBureau,gwaTas,gwaTasName,agencyName,betc,betcName,effectiveDate,suspendDate,credit,adjustmentBetc,starTas,starDeptReg,starDeptXfr,starMainAccount,transactionType,accountType,accountTypeDescription,fundType,fundTypeDescription,blankComma
        cronSchedule: "*/60 * * * * *"
        encoding: Cp1252
        fileUploadRootDirectory: /Users/tim/git-repositories/spring-batch-poc-stuff
        intervalInSeconds: 60
        skipLimit: 2
# http://localhost:8085/batch-processor/h2-console/